# Generated by Django 5.1.5 on 2025-01-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='content',
            new_name='comments',
        ),
    ]
