# Generated by Django 5.1.5 on 2025-01-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_content_articlecomment_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='comments',
            new_name='comment',
        ),
    ]
