# Generated by Django 5.1.5 on 2025-01-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_comments_articlecomment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Bülten',
                'verbose_name_plural': 'Bülten',
                'ordering': ['-created'],
            },
        ),
    ]
