# Generated by Django 5.1.5 on 2025-01-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_newslettermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
