# Generated by Django 5.1.5 on 2025-01-19 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_articlemodel_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='created',
        ),
    ]
