# Generated by Django 5.1.5 on 2025-03-15 18:53

import autoslug.fields
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Kategori')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique_with=('created',))),
            ],
            options={
                'verbose_name': 'Ürün Kategorisi',
                'verbose_name_plural': 'Ürün Kategorisi',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/')),
                ('name', models.CharField(max_length=100, verbose_name='Ürün adı')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='İçerik')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stok')),
                ('price', models.FloatField(verbose_name='Fiyat')),
                ('ordered', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Satış adeti')),
                ('is_stock', models.BooleanField(default=True, verbose_name='Stokta var mı ?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.productcategory', verbose_name='Ürün Kategorisi')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
    ]
