# Generated by Django 5.1.5 on 2025-01-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('genel', 'description'), ('facebook', 'keywords'), ('twitter', 'twitter'), ('canonical', 'og:url')], max_length=100, verbose_name='Tag Türü')),
                ('name', models.CharField(max_length=50, verbose_name='Tag Adı')),
                ('content', models.TextField(verbose_name='Tag İçeriği')),
            ],
        ),
    ]
