# Generated by Django 5.1.5 on 2025-01-19 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_metatags'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatags',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_tags', to='base.home'),
        ),
    ]
