# Generated by Django 5.1.5 on 2025-01-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_metatags_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metatags',
            options={'verbose_name': 'Meta Tag', 'verbose_name_plural': 'Meta Taglar'},
        ),
        migrations.AlterField(
            model_name='metatags',
            name='tag',
            field=models.CharField(choices=[('genel', 'genel'), ('facebook', 'facebook'), ('twitter', 'twitter'), ('google', 'google'), ('canonical', 'canonical')], max_length=100, verbose_name='Tag türü'),
        ),
    ]
