# Generated by Django 5.1.5 on 2025-01-19 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_metatags_options_alter_metatags_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='facebook, twitter, instagram, linkedin, github', max_length=100, verbose_name='Social Medya')),
                ('url', models.URLField(verbose_name='Social Medya URL')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='base.home')),
            ],
            options={
                'verbose_name': 'Social Medya',
                'verbose_name_plural': 'Social Medya',
            },
        ),
    ]
