# Generated by Django 5.1.5 on 2025-01-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_socialnetwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon_type',
            field=models.CharField(choices=[('fa', 'Fontawesome'), ('bi', 'Bootstrap')], default='bi', max_length=10),
        ),
    ]
