# Generated by Django 5.1.5 on 2025-01-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_services_icon_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='icon_type',
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.FileField(upload_to='Services/icons/', verbose_name='Hizmet Icon'),
        ),
    ]
