# Generated by Django 5.1.5 on 2025-01-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_services_icon_type_alter_services_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(help_text="Ör : bi bi-binoculars <h6>Daha fazlası için, <a href='https://icons.getbootstrap.com/' target='_blank'>Bootstrap iconları</a>, <a href='https://fontawesome.com/search' target='_blank'>Fontawesome iconları</a></h6>", max_length=50, verbose_name='Icon sınıfı'),
        ),
    ]
