# Generated by Django 5.1.5 on 2025-01-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_services_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon_type',
            field=models.CharField(choices=[('fa', 'Fontawesome'), ('bi', 'Bootstrap')], default='bi', help_text="<h6>Daha fazlası için, <a href='https://icons.getbootstrap.com/' target='_blank'>Bootstrap iconları</a>, <a href='https://fontawesome.com/search' target='_blank'>Fontawesome iconları</a></h6>", max_length=2, verbose_name='İcon Türü'),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(help_text='Ör : bi bi-binoculars', max_length=50, verbose_name='Icon Sınıfı'),
        ),
    ]
